name: women_safety_app
description: "AI-Powered Women Safety App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Backend & Network
  supabase_flutter: ^2.8.0
  http: ^1.2.0

  # Location & Connectivity (For SOS & Offline SMS)
  geolocator: ^13.0.1
  geolocator_android: ^4.6.1
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4

  # AI / ML & Audio
  tflite_flutter: ^0.10.4
  record: ^6.0.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.0

  # Device & Security Features
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  flutter_local_notifications: ^17.0.0

  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/vosk-model-small-en-us-0.15.zip
    - assets/models/vosk-model-small-hi-0.22.zip
    - assets/models/yamnet.tflite
    - assets/models/distress_classifier.tflite
    - assets/sounds/alarm.wav